### ISSUE TITLE
Icons on sketchybarrc

### ISSUE THREAD

**Issue by rxzheng** [sertdfyguhi/dotfiles#1]
Hi, 
I am a bit confused on how to get the icons working on sketchybar. I was copied your icons, but they do not appear.

Where can I find these icons, and how would I put them onto the bar?
![Uploading Screenshot 2023-12-06 at 6.18.48 pm.png…]()

**Comment by rxzheng** [comment]
https://i.postimg.cc/QN1k7cV5/Screenshot-2023-12-06-at-6-18-48-pm.png

**Comment by rxzheng** [comment]
Never mind, you just have to install the font.

```bash
brew tap homebrew/cask-fonts
brew install --cask font-hack-nerd-font
```

**Comment by rxzheng** [comment]
Some icons work, and others do not. 
https://i.postimg.cc/kGrq00dj/Screenshot-2023-12-06-at-6-36-42-pm.png

**Comment by sertdfyguhi** [comment]
Can't see the image, super low quality. You could try downloading a nerd font from [here](https://www.nerdfonts.com/font-downloads).

**Comment by rxzheng** [comment]
This is what I did:
```bash
git clone --depth 1 https://github.com/ryanoasis/nerd-fonts.git
cd nerd-fonts
./install.sh
```
and it didn't work after reloading sketchybar.
Which nerd font did you install from that website?
thanks for your response though.

**Comment by rxzheng** [comment]
[Screenshot-2023-12-07-at-7-53-39-am.png](https://postimg.cc/MvdknQQr)

**Comment by rxzheng** [comment]
Hopefully that isn't as pixelated.

**Comment by sertdfyguhi** [comment]
You need to first go onto https://www.nerdfonts.com/font-downloads and press download any of the fonts listed. Then, extract the zip and install all the .ttf files by double clicking it. Now, go to your sketchybarrc and change the FONT variable to the font name listed on the website. Font name should end in "Nerd Font". If you install the CaskaydiaCode Nerd Font you don't need to change the font in the sketchybarrc.

**Comment by rxzheng** [comment]
Oh thank you so much!
